sudo: required
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to install dependencies
install:
 - "pip install -r requirements.txt"
 - "pip install pylint"
before_script: ./test/inst.sh
# command to run tests
script: 
 - pv="$(python --version 2>&1)"
 - pv1="Python 2.6"
 - pv2="Python 3.2"
 - pylint letsacme.py ;if [[ ! $? -eq 1 ]]; then echo 'pylint success!';elif [[ "$pv" = "$pv1"* || "$pv" = "$pv2"* ]]; then echo "pylint is broken in 2.6 and 3.2 does not recognize u'', pylint error for 2.6 and 3.2 should be ignored";else false; fi
 - ./test/travis_check.sh

